// ========== MAPPING ==========
export const SOLVERS: string[] = [
  "Find Largest Prime Factor",
  "Subarray with Maximum Sum",
  "Spiralize Matrix",
  "Array Jumping Game",
  "Array Jumping Game II",
  "Minimum Path Sum in a Triangle",
  "Unique Paths in a Grid I",
  "Unique Paths in a Grid II",
  "Generate IP Addresses",
  "Merge Overlapping Intervals",
  "Proper 2-Coloring of a Graph",
  "Sanitize Parentheses in Expression",
  "Total Ways to Sum",
  "Total Ways to Sum II",
  "Algorithmic Stock Trader I",
  "Algorithmic Stock Trader II",
  "Algorithmic Stock Trader III",
  "Algorithmic Stock Trader IV",
  "Shortest Path in a Grid",
  "Encryption I: Caesar Cipher",
  "Encryption II: Vigenère Cipher",
  "HammingCodes: Encoded Binary to Integer",
  "Compression I: RLE Compression",
];
